TIER = ['UNRANKED','IRON','BRONZE','SILVER','GOLD','PLATINUM','EMERALD','DIAMOND','MASTER','GRANDMASTER','CHALLENGER']
POSITION = ['ANY','TOP','JUNGLE','MID','ADC','SUP']
MIKE = ['UNAVAILABLE','AVAILABLE']