DICT = {
    "block": "block_id",
    "board": "board_id",
    "board_game_style": "board_game_style_id",
    "champion": "champion_id",
    "chat": "chat_id",
    "chatroom": "chatroom_id",
    "email_verify_record": "record_id",
    "friend": "friend_id",
    "friend_request": "friend_request_id",
    "game_style": "gamestyle_id",
    "manner_keyword": "manner_keyword_id",
    "manner_rating": "manner_rating_id",
    "manner_rating_keyword": "manner_rating_keyword_id",
    "matching_record": "matching_uuid",
    "member": "member_id",
    "member_champion": "member_champion_id",
    "member_chatroom": "member_chatroom_id",
    "member_game_style": "member_gamestyle_id",
    "notification": "notification_id",
    "notification_type": "notification_type_id",
    "refresh_token": "refresh_token_id",
    "report": "report_id",
    "report_type_mapping": "report_type_mapping_id"
}